on:
  pull_request:
     paths:
        - '**/validator*'
   
jobs:

   job1:
      name: Test
      runs-on: ubuntu-latest
      env:
         PATTERN: '@[a-z0-9]+'
      outputs:
          result: ${{ steps.one.outputs.result}}
      steps:
          - uses: actions/checkout@v3
            with:
                fetch-depth: 2

          - id: one
            run: |
             d=$(git diff -G$PATTERN HEAD^1 HEAD)

             echo "$d"
             echo "$(git show HEAD^1)"

             if [[ -n $d ]]; then
               echo "result=yes" >> $GITHUB_OUTPUT
             else
              exit 1
             fi
   
   job2:
      name: test github output
      needs: job1
      runs-on: ubuntu-latest
      if: needs.job1.outputs.result == 'yes'
      steps:
         - run: echo "it worked"

            
    
