on:
  pull_request:
     paths:
        - '**/validator*'
jobs:

   test_diff:
      name: Test
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
            with:
                fetch_depth: 2
          - run: |
             mydiff = git diff HEAD^ HEAD
             echo "$mydiff" >> $GITHUB_OUTPUT
    
