on:
  pull_request:
     paths:
        - '**/validator*'
env:
   GITHUB_PAT: ''
jobs:

   job1:
      name: Test
      runs-on: ubuntu-latest
      env:
         PATTERN: '@[a-z0-9]+'
         GH_TOKEN: ${{ github.token }}
      outputs:
          result: ${{ steps.one.outputs.result}}
      steps:
          - uses: actions/checkout@v3
            with:
                fetch-depth: 2

          - id: one
            run: |
             d=$(gh pr diff | grep -E $PATTERN)

             echo "$d"
             if [[ -n $d ]]; then
               echo "result=yes" >> $GITHUB_OUTPUT
             else
              exit 1
             fi

   set_credentials:
      name: Get and set PAT
      runs-on: ubuntu-latest
      permissions:
         contents: read
         pull-requests: write
      env:
        GH_TOKEN: ${{ github.token }}
        OWNER: ${{ github.repository_owner}}
        REPO: ${{ github.repository }}
        SECRET_NAME: FOO

      steps:
        - name: Get github pat from secrets
          run: |
           $( gh api \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/$OWNER/$REPO/actions/secrets/$SECRET_NAME ) >> $GITHUB_PAT
           echo $GITHUB_PAT
            
    
